logging:
    level:
        org:
            atmosphere: warn
server:
    port: ${PORT:8080}
spring:
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      password: ${SPRING_DATASOURCE_USERNAME}
      username: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        defer-datasource-initialization: false
        hibernate:
            ddl-auto: create-drop
vaadin:
    launch-browser: false
    vaadin.allowed-packages: com.en